# Autor: Cristtopher Quintana T. <cquintana@axxezo.com>
image: node:boron

pipelines:
  default:
    - step:
        caches:
          - node
        script:
            - node -v
            - npm install -g @angular/cli@1.1.1
            - npm install
            #- ng lint
            - docker login $CONTAINER_REGISTRY_URI -u $CONTAINER_REGISTRY_USERNAME -p $CONTAINER_REGISTRY_PASSWORD
            - VERSION=v1
            - docker build -t $CONTAINER_REGISTRY_URI/$IMAGE_NAME:$VERSION -t $CONTAINER_REGISTRY_URI/$IMAGE_NAME:latest .
            - docker push $CONTAINER_REGISTRY_URI/$IMAGE_NAME:$VERSION
            - docker push $CONTAINER_REGISTRY_URI/$IMAGE_NAME:latest
options:
  docker: true
